-- 032_seed_bancos_e_empresas.sql
-- Cadastro em massa de bancos (tabela FEBRABAN/BACEN, 109 instituições) e das
-- 3 primeiras empresas do grupo Cangaia, solicitados pelo usuário.
--
-- Bancos: ON CONFLICT (bank_code) DO NOTHING porque 3 códigos (001, 341, 237)
-- já existem via o seed de arranque da aplicação (backend/src/db/seed.js).
-- bank_type (publico/estrangeiro/privado) é classificação best-effort — campo
-- nullable e editável a qualquer momento pela tela de Governança > Bancos.

INSERT INTO banks (id, bank_code, bank_name, bank_type, status) VALUES
  ('bank_001', '001', 'Banco do Brasil S.A.', 'publico', 'ativo'),
  ('bank_003', '003', 'Banco da Amazônia S.A.', 'publico', 'ativo'),
  ('bank_004', '004', 'Banco do Nordeste do Brasil S.A.', 'publico', 'ativo'),
  ('bank_007', '007', 'Banco Nacional de Desenvolvimento Econômico e Social - BNDES', 'publico', 'ativo'),
  ('bank_012', '012', 'Banco Inbursa S.A.', 'estrangeiro', 'ativo'),
  ('bank_021', '021', 'BANESTES S.A. Banco do Estado do Espírito Santo', 'publico', 'ativo'),
  ('bank_024', '024', 'Banco de Pernambuco S.A. - BANDEPE', 'privado', 'ativo'),
  ('bank_025', '025', 'Banco Alfa S.A.', 'privado', 'ativo'),
  ('bank_029', '029', 'Banco Itaú Consignado S.A.', 'privado', 'ativo'),
  ('bank_033', '033', 'Banco Santander (Brasil) S.A.', 'estrangeiro', 'ativo'),
  ('bank_036', '036', 'Banco Bradesco BBI S.A.', 'privado', 'ativo'),
  ('bank_037', '037', 'Banco do Estado do Pará S.A.', 'publico', 'ativo'),
  ('bank_040', '040', 'Banco Cargill S.A.', 'estrangeiro', 'ativo'),
  ('bank_041', '041', 'Banco do Estado do Rio Grande do Sul S.A. (Banrisul)', 'publico', 'ativo'),
  ('bank_047', '047', 'Banco do Estado de Sergipe S.A.', 'publico', 'ativo'),
  ('bank_062', '062', 'Hipercard Banco Múltiplo S.A.', 'privado', 'ativo'),
  ('bank_063', '063', 'Banco Bradescard S.A.', 'privado', 'ativo'),
  ('bank_065', '065', 'Banco Andbank (Brasil) S.A.', 'estrangeiro', 'ativo'),
  ('bank_066', '066', 'Banco Morgan Stanley S.A.', 'estrangeiro', 'ativo'),
  ('bank_069', '069', 'Banco Crefisa S.A.', 'privado', 'ativo'),
  ('bank_070', '070', 'BRB - Banco de Brasília S.A.', 'publico', 'ativo'),
  ('bank_074', '074', 'Banco J. Safra S.A.', 'privado', 'ativo'),
  ('bank_075', '075', 'Banco ABN Amro S.A.', 'estrangeiro', 'ativo'),
  ('bank_077', '077', 'Banco Inter S.A.', 'privado', 'ativo'),
  ('bank_082', '082', 'Banco Topázio S.A.', 'privado', 'ativo'),
  ('bank_083', '083', 'Banco da China Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_094', '094', 'Banco Finaxis S.A.', 'privado', 'ativo'),
  ('bank_095', '095', 'Banco Travelex S.A.', 'estrangeiro', 'ativo'),
  ('bank_096', '096', 'Banco B3 S.A.', 'privado', 'ativo'),
  ('bank_102', '102', 'Banco XP S.A.', 'privado', 'ativo'),
  ('bank_104', '104', 'Caixa Econômica Federal', 'publico', 'ativo'),
  ('bank_107', '107', 'Banco BOCOM BBM S.A.', 'estrangeiro', 'ativo'),
  ('bank_119', '119', 'Banco Western Union do Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_120', '120', 'Banco Rodobens S.A.', 'privado', 'ativo'),
  ('bank_121', '121', 'Banco Agibank S.A.', 'privado', 'ativo'),
  ('bank_125', '125', 'Banco Genial S.A.', 'privado', 'ativo'),
  ('bank_128', '128', 'Braza Bank S.A. Banco de Câmbio', 'privado', 'ativo'),
  ('bank_129', '129', 'UBS Brasil Banco de Investimento S.A.', 'estrangeiro', 'ativo'),
  ('bank_144', '144', 'Ebury Banco de Câmbio S.A.', 'estrangeiro', 'ativo'),
  ('bank_169', '169', 'Banco Olé Bonsucesso Consignado S.A.', 'privado', 'ativo'),
  ('bank_184', '184', 'Banco Itaú BBA S.A.', 'privado', 'ativo'),
  ('bank_204', '204', 'Banco Bradesco Cartões S.A.', 'privado', 'ativo'),
  ('bank_208', '208', 'Banco BTG Pactual S.A.', 'privado', 'ativo'),
  ('bank_212', '212', 'Banco Original S.A.', 'privado', 'ativo'),
  ('bank_217', '217', 'Banco John Deere S.A.', 'estrangeiro', 'ativo'),
  ('bank_218', '218', 'Banco BS2 S.A.', 'privado', 'ativo'),
  ('bank_222', '222', 'Banco Credit Agricole Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_224', '224', 'Banco Fibra S.A.', 'privado', 'ativo'),
  ('bank_233', '233', 'Banco Cifra S.A.', 'privado', 'ativo'),
  ('bank_237', '237', 'Banco Bradesco S.A.', 'privado', 'ativo'),
  ('bank_243', '243', 'Banco Master S.A.', 'privado', 'ativo'),
  ('bank_246', '246', 'Banco ABC Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_249', '249', 'Banco Investcred Unibanco S.A.', 'privado', 'ativo'),
  ('bank_250', '250', 'BCV - Banco de Crédito e Varejo S.A.', 'privado', 'ativo'),
  ('bank_254', '254', 'Paraná Banco S.A.', 'privado', 'ativo'),
  ('bank_260', '260', 'Nu Pagamentos S.A. (Nubank)', 'privado', 'ativo'),
  ('bank_265', '265', 'Banco Fator S.A.', 'privado', 'ativo'),
  ('bank_269', '269', 'Banco HSBC S.A.', 'estrangeiro', 'ativo'),
  ('bank_290', '290', 'Pagseguro Internet S.A.', 'privado', 'ativo'),
  ('bank_299', '299', 'Banco Afinz S.A. Banco Múltiplo', 'privado', 'ativo'),
  ('bank_318', '318', 'Banco BMG S.A.', 'privado', 'ativo'),
  ('bank_320', '320', 'Bank Of China (Brasil) Banco Múltiplo S.A.', 'estrangeiro', 'ativo'),
  ('bank_336', '336', 'Banco C6 S.A.', 'privado', 'ativo'),
  ('bank_341', '341', 'Itaú Unibanco S.A.', 'privado', 'ativo'),
  ('bank_348', '348', 'Banco XP S.A.', 'privado', 'ativo'),
  ('bank_366', '366', 'Banco Société Générale Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_370', '370', 'Banco Mizuho do Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_376', '376', 'Banco J. P. Morgan S.A.', 'estrangeiro', 'ativo'),
  ('bank_386', '386', 'Nu Financeira S.A.', 'privado', 'ativo'),
  ('bank_389', '389', 'Banco Mercantil do Brasil S.A.', 'privado', 'ativo'),
  ('bank_394', '394', 'Banco Bradesco Financiamentos S.A.', 'privado', 'ativo'),
  ('bank_399', '399', 'Kirton Bank S.A. - Banco Múltiplo', 'privado', 'ativo'),
  ('bank_412', '412', 'Banco Capital S.A.', 'privado', 'ativo'),
  ('bank_422', '422', 'Banco Safra S.A.', 'privado', 'ativo'),
  ('bank_456', '456', 'Banco MUFG Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_464', '464', 'Banco Sumitomo Mitsui Brasileiro S.A.', 'estrangeiro', 'ativo'),
  ('bank_473', '473', 'Banco Caixa Geral - Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_477', '477', 'Citibank N.A.', 'estrangeiro', 'ativo'),
  ('bank_479', '479', 'Banco ItauBank S.A', 'privado', 'ativo'),
  ('bank_487', '487', 'Deutsche Bank S.A. - Banco Alemão', 'estrangeiro', 'ativo'),
  ('bank_488', '488', 'JPMorgan Chase Bank, National Association', 'estrangeiro', 'ativo'),
  ('bank_496', '496', 'BBVA Brasil Banco de Investimento S.A.', 'estrangeiro', 'ativo'),
  ('bank_505', '505', 'Banco Credit Suisse (Brasil) S.A.', 'estrangeiro', 'ativo'),
  ('bank_600', '600', 'Banco Luso Brasileiro S.A.', 'estrangeiro', 'ativo'),
  ('bank_604', '604', 'Banco Industrial do Brasil S.A.', 'privado', 'ativo'),
  ('bank_610', '610', 'Banco VR S.A.', 'privado', 'ativo'),
  ('bank_611', '611', 'Banco Paulista S.A.', 'privado', 'ativo'),
  ('bank_612', '612', 'Banco Guanabara S.A.', 'privado', 'ativo'),
  ('bank_613', '613', 'Omni Banco S.A.', 'privado', 'ativo'),
  ('bank_623', '623', 'Banco Pan S.A.', 'privado', 'ativo'),
  ('bank_626', '626', 'Banco Ficsa S.A.', 'privado', 'ativo'),
  ('bank_630', '630', 'Banco Smartbank S.A.', 'privado', 'ativo'),
  ('bank_633', '633', 'Banco Rendimento S.A.', 'privado', 'ativo'),
  ('bank_634', '634', 'Banco Triângulo S.A.', 'privado', 'ativo'),
  ('bank_641', '641', 'Banco Alvorada S.A.', 'privado', 'ativo'),
  ('bank_643', '643', 'Banco Pine S.A.', 'privado', 'ativo'),
  ('bank_653', '653', 'Banco Indusval S.A.', 'privado', 'ativo'),
  ('bank_654', '654', 'Banco Digimais S.A.', 'privado', 'ativo'),
  ('bank_655', '655', 'Banco Votorantim S.A.', 'privado', 'ativo'),
  ('bank_707', '707', 'Banco Daycoval S.A.', 'privado', 'ativo'),
  ('bank_712', '712', 'Banco Ourinvest S.A.', 'privado', 'ativo'),
  ('bank_745', '745', 'Banco Citibank S.A.', 'estrangeiro', 'ativo'),
  ('bank_746', '746', 'Banco Modal S.A.', 'privado', 'ativo'),
  ('bank_747', '747', 'Banco Rabobank International Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_748', '748', 'Sicredi (Sistema de Crédito Cooperativo)', 'privado', 'ativo'),
  ('bank_751', '751', 'Scotiabank Brasil S.A. Banco Múltiplo', 'estrangeiro', 'ativo'),
  ('bank_752', '752', 'Banco BNP Paribas Brasil S.A.', 'estrangeiro', 'ativo'),
  ('bank_755', '755', 'Bank of America Merrill Lynch Banco Múltiplo S.A.', 'estrangeiro', 'ativo'),
  ('bank_756', '756', 'Sicoob (Sistema de Cooperativas de Crédito do Brasil)', 'privado', 'ativo')
ON CONFLICT (bank_code) DO NOTHING;

-- Novo grupo econômico para as 3 empresas abaixo (não reaproveita o 'Grupo Demo' de teste).
INSERT INTO groups (id, group_name, cnpj_group, description, status) VALUES
  ('grp_cangaia', 'Grupo Cangaia', NULL, NULL, 'ativo')
ON CONFLICT (id) DO NOTHING;

-- Entidades componentes do Grupo Cangaia.
INSERT INTO company_entities (id, group_id, entity_name, document_number, document_type, entity_type, status) VALUES
  ('ent_agro_cangaia', 'grp_cangaia', 'Agro Cangaia Armazém Ltda.', '38.539.559/0001-67', 'CNPJ', 'empresa', 'ativa'),
  ('ent_terminal_amazonia_para', 'grp_cangaia', 'Terminal Amazônia Pará Ltda.', '36.940.852/0001-06', 'CNPJ', 'empresa', 'ativa'),
  ('ent_guilherme_frota_carvalho', 'grp_cangaia', 'Guilherme Frota Carvalho', '104.435.156-03', 'CPF', 'pf', 'ativa')
ON CONFLICT (id) DO NOTHING;
